# ニューラルネットワーク（ANN）

### ライブラリのインポート

In [13]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [14]:
tf.__version__

'2.10.0'

## Part 1 - データの前処理

### データセットのインポート

In [15]:
dataset = pd.read_csv('Boot-camp/Data/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [16]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [17]:
print(y)

[1 0 1 ... 1 1 0]


### カテゴリ変数のエンコーディング

 "Gender"列のエンコーディング

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [19]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


 "Geography" 列のエンコーディング

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [21]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### フィーチャースケーリング

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [23]:
print(X)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


### 訓練用とテスト用へのデータセットの分割

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - ANNの構築

### ANNのイニシャライズ

In [25]:
ann = tf.keras.models.Sequential()

### 入力層と、一つ目の隠れ層の追加

In [26]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### 二つ目の隠れ層の追加

In [27]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### 出力層の追加

In [28]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## ANNの訓練（学習）

### ANNのコンパイル

In [29]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### 訓練用データセットを使ったANNの訓練

In [30]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 811us/step - loss: 0.5683 - accuracy: 0.7765
Epoch 2/100
250/250 [==============================] - 0s 759us/step - loss: 0.4667 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 761us/step - loss: 0.4460 - accuracy: 0.7962
Epoch 4/100
250/250 [==============================] - 0s 757us/step - loss: 0.4356 - accuracy: 0.7969
Epoch 5/100
250/250 [==============================] - 0s 755us/step - loss: 0.4280 - accuracy: 0.8021
Epoch 6/100
250/250 [==============================] - 0s 769us/step - loss: 0.4214 - accuracy: 0.8030
Epoch 7/100
250/250 [==============================] - 0s 758us/step - loss: 0.4145 - accuracy: 0.8030
Epoch 8/100
250/250 [==============================] - 0s 757us/step - loss: 0.4054 - accuracy: 0.8056
Epoch 9/100
250/250 [==============================] - 0s 775us/step - loss: 0.3956 - accuracy: 0.8114
Epoch 10/100
250/250 [==============================] - 0s 847us/step - l

## Part 4 - 結果の予測とモデルの評価

### テストデータによる結果の予測

In [31]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 645us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### 混同行列の作成

In [32]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1528   67]
 [ 199  206]]
