In [1]:
import numpy as np

In [2]:
np.random.randint(0,100,size=10) ##0から100までの乱数を10個生成

array([32, 86, 90, 93, 49, 58, 82,  2, 75, 20])

In [3]:
np.random.randn(2,3) ##正規分布に従う乱数を生成(2次元×3次元)

array([[ 1.16601608,  0.37371735,  0.33854836],
       [-1.02804096, -0.98731252,  1.58535851]])

In [4]:
np.random.seed(1) ##乱数のシードを固定
np.random.randint(0,100,size=10)  ##シードを固定すると毎回同じ乱数が生成される

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])