In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
number = 10

In [3]:
arr1 + arr2 

array([5, 7, 9])

In [4]:
arr1 * arr2

array([ 4, 10, 18])

In [5]:
arr1 + number

array([11, 12, 13])