In [1]:
import numpy as np

In [2]:
arr = np.array([5,-2,7,4,1])
print(arr)

[ 5 -2  7  4  1]


In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.ndim ##次元数

1

In [5]:
arr.shape ##各次元の要素の数

(5,)

In [6]:
arr[0] ##pythonのリストと同じようにアクセスできる

5

In [7]:
arr[1:4] ##スライスもできる

array([-2,  7,  4])

In [15]:
print(arr.max()) ##最大値
print(arr.min()) ##最小値

7
-2


In [16]:
print(arr.argmax()) ##最大値のインデックス
print(arr.argmin()) ##最小値のインデックス

2
1


In [8]:
arr2 = np.array([[3,4,5],[6,7,8]])
print(arr2)

[[3 4 5]
 [6 7 8]]


In [9]:
print(arr2[0,2]) #0番目の行2番目の要素

5


In [10]:
arr2[1,1] = 99 # 1番目の行1番目の要素を99に変更
print(arr2)

[[ 3  4  5]
 [ 6 99  8]]


## 条件付き抽出

In [11]:
arr11 = np.array([1, 2, 3, 4, 5, 6])

In [12]:
arr11 < 3

array([ True,  True, False, False, False, False])

In [13]:
arr11[arr11 < 3] ##条件を満たす要素のみ取り出す

array([1, 2])