In [11]:
import numpy as np

In [12]:
arr3 = np.array([1, 2, 3, 4, 5, 6])
print(arr3)

[1 2 3 4 5 6]


In [13]:
arr3.reshape(6, 1) ## 6行1列に変換

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [14]:
arr4 = np.array([1, 2, 3])
arr5 = np.array([4, 5, 6])

In [15]:
arr6 = np.concatenate([arr4, arr5]) ##concatenateで結合できる
arr6

array([1, 2, 3, 4, 5, 6])

In [16]:
arr7, arr8 = np.split(arr6, [3]) ##splitで分割できる

In [17]:
arr7

array([1, 2, 3])

In [18]:
arr8

array([4, 5, 6])