In [1]:
import numpy as np

In [2]:
arr9 = np.array([1, 2, 3, 4, 5, 6])
arr10 = np.array([[1, 2, 3], [4, 5, 6]]) ##2次元配列の場合
print(arr9)
print(arr10)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [3]:
np.mean(arr9) ##平均(1次元配列)

3.5

In [4]:
np.mean(arr10, axis=0) ##行(縦)ごとの平均(2次元配列)

array([2.5, 3.5, 4.5])

In [5]:
np.mean(arr10, axis=1) ##列(横)ごとの平均(２次元配列)

array([2., 5.])

In [6]:
np.sum(arr9) ##合計(1次元配列)

21

In [9]:
np.amin(arr9) ##最小値(1次元配列)

1

In [10]:
np.amax(arr9) ##最大値(1次元配列)

6

In [11]:
np.median(arr9) ##中央値(1次元配列)

3.5

In [7]:
np.var(arr9) ##分散

2.9166666666666665

In [8]:
np.std(arr9) ##標準偏差

1.707825127659933